<?xml version="1.0" encoding="UTF-8"?><testrun name="ArqueroTest" project="TP3" tests="83" started="83" failures="8" errors="0" ignored="0">
  <testsuite name="personaje.ArqueroTest" time="0.002">
    <testcase name="baseAtacadoPorArqueroConCapaYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYEscudoAtacadoPorArqueroBase" classname="personaje.ArqueroTest" time="0.001">
      <failure>java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at personaje.ArqueroTest.conPunialYEscudoAtacadoPorArqueroBase(ArqueroTest.java:675)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="conCapaYEscudoAtacadoPorArqueroConEscudo" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparCapaEscudoPunialTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaYEscudoAtacadoPorArqueroConEscudoYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="puedeRestaurarEnergia" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaAtacadoPorArqueroConCapaYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYEscudoAtacadoPorArqueroConCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaYEscudoAtacadoPorArqueroConPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYCapaAtacadoPorArqueroBase" classname="personaje.ArqueroTest" time="0.0">
      <failure>java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at personaje.ArqueroTest.conPunialYCapaAtacadoPorArqueroBase(ArqueroTest.java:740)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="conPunialCapaYEscudoAtacadoPorArqueroConEscudoYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaAtacadoPorArqueroBase" classname="personaje.ArqueroTest" time="0.0">
      <failure>java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at personaje.ArqueroTest.conCapaAtacadoPorArqueroBase(ArqueroTest.java:552)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="noAtacarMuertos" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialCapaYEscudoAtacadoPorArqueroConCapaYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYEscudoAtacadoPorArqueroConCapaYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="restaurarEnergia" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaAtacadoPorArqueroConCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conEscudoAtacadoPorArqueroConCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparPunialCapaTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaYEscudoAtacadoPorArqueroConEscudoYCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialAtacadoPorArqueroConEscudoYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYCapaAtacadoPorArqueroConEscudoYCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialAtacadoPorArqueroConEscudo" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialCapaYEscudoAtacadoPorArqueroBase" classname="personaje.ArqueroTest" time="0.0">
      <failure>java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at personaje.ArqueroTest.conPunialCapaYEscudoAtacadoPorArqueroBase(ArqueroTest.java:806)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="baseAtacadoPorArqueroConCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialAtacadoPorArqueroBase" classname="personaje.ArqueroTest" time="0.0">
      <failure>java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at personaje.ArqueroTest.conPunialAtacadoPorArqueroBase(ArqueroTest.java:490)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="noPoderAtacarAgotado" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYEscudoAtacadoPorArqueroConEscudoYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparPunialTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialCapaYEscudoAtacadoPorArqueroConEscudo" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaYEscudoAtacadoPorArqueroBase" classname="personaje.ArqueroTest" time="0.0">
      <failure>java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at personaje.ArqueroTest.conCapaYEscudoAtacadoPorArqueroBase(ArqueroTest.java:611)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="distanciaNoValidaParaCombate" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialAtacadoPorArqueroConPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conEscudoAtacadoPorArqueroConCapaYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="baseAtacadoPorArqueroBase" classname="personaje.ArqueroTest" time="0.0">
      <failure>java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at personaje.ArqueroTest.baseAtacadoPorArqueroBase(ArqueroTest.java:364)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="distanciaValidaParaCombate" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conEscudoAtacadoPorArqueroConEscudoYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conEscudoAtacadoPorArqueroBase" classname="personaje.ArqueroTest" time="0.0">
      <failure>java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at personaje.ArqueroTest.conEscudoAtacadoPorArqueroBase(ArqueroTest.java:424)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="conPunialCapaYEscudoAtacadoPorArqueroConPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="baseAtacadoPorArqueroConEscudoYCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="noPoderAtacarEstandoMuerto" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYEscudoAtacadoPorArqueroConEscudo" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaAtacadoPorArqueroConEscudoYCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparEscudoPunialTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparCapaPunialTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparCapaPunialEscudoTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialCapaYEscudoAtacadoPorArqueroConEscudoYCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYEscudoAtacadoPorArqueroConEscudoYCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYEscudoAtacadoPorArqueroConPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparCapaTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialAtacadoPorArqueroConCapaYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="noAtacarAgotado" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaYEscudoAtacadoPorArqueroConCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="noAtacarEstandoMuerto" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYCapaAtacadoPorArqueroConEscudoYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialAtacadoPorArqueroConCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYCapaAtacadoPorArqueroConEscudo" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conEscudoAtacadoPorArqueroConEscudo" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="crearNuevoTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparEscudoTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="baseAtacadoPorArqueroConEscudoYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="agotarEnergia" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYCapaAtacadoPorArqueroConPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conEscudoAtacadoPorArqueroConPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYCapaAtacadoPorArqueroConCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaAtacadoPorArqueroConEscudo" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conEscudoAtacadoPorArqueroConEscudoYCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaAtacadoPorArqueroConEscudoYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaAtacadoPorArqueroConPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparPunialCapaEscudoTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conCapaYEscudoAtacadoPorArqueroConCapaYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="baseAtacadoPorArqueroConEscudo" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="noSeAutoAtaca" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialYCapaAtacadoPorArqueroConCapaYPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="noPoderAtacarMuertos" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparCapaEscudoTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparEscudoCapaTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="baseAtacadoPorArqueroConPunial" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparEscudoCapaPunialTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialCapaYEscudoAtacadoPorArqueroConCapaPunialYEscudo" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="equiparPunialEscudoTest" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialAtacadoPorArqueroConEscudoYCapa" classname="personaje.ArqueroTest" time="0.0"/>
    <testcase name="conPunialCapaYEscudoAtacadoPorArqueroConCapa" classname="personaje.ArqueroTest" time="0.0"/>
  </testsuite>
</testrun>
